__default__:
  jobname: "smk-{rule}-{wildcards.sample}"
  ncpus: 2
  mem: "16GB"
  walltime: "12:00:00"
  storage: "gdata/pq84+scratch/pq84"
  account: "jw1542"
  queue: "normalbw"
  email: "jacob.westaway@menzies.edu.au"
  mailon: "ea"
  jobout: "oe"

bwa_map:
  ncpus: 5
  mem: "50GB"
  walltime: "24:00:00"

realigner_target_creator: 
  ncpus: 5
  mem: "50GB"
  walltime: "24:00:00"